### ISSUE TITLE
Error taking picture 

### ISSUE THREAD

**Issue by diegoampessan** [yazeed44/MultiImagePicker#27]
Hello, I am implementing a library in my project however when taking a picture he bursts the following error

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
            at net.yazeed44.imagepicker.model.ImageEntry$Builder.from(ImageEntry.java:52)
            at net.yazeed44.imagepicker.model.ImageEntry.from(ImageEntry.java:26)
            at net.yazeed44.imagepicker.ui.PickerActivity.onActivityResult(PickerActivity.java:227)
            at android.app.Activity.dispatchActivityResult(Activity.java:6549)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:4054)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3380)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3425)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4462)
            at android.app.ActivityThread.access$1000(ActivityThread.java:177)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by yazeed44** [comment]
Android version + Phone name + library version ?

**Comment by diegoampessan** [comment]
Android 5.0.1 
Samsung Galaxy 4 (GT-I9505) 
Lib versions 1.0.1 or 1.1 or 1.1.1

**Comment by diegoampessan** [comment]
I tried to run your sample code, but explodes the same exception mentioned

**Comment by yazeed44** [comment]
Ok i will fix that in 1.1.2

**Comment by diegoampessan** [comment]
Thanks! Any idea why the problem happens? I tried to debug but unable to find it because of the error.

**Comment by yazeed44** [comment]
It's probably because some manufacturers take different approach to ACTIO_IMAGE_CAPTURE

**Comment by diegoampessan** [comment]
Strange, I implemented the call ACTION_IMAGE_CAPTURE other than by the library and the resultCode in onActivityResult is OK. However by the lib resultCode equals -1

**Comment by yazeed44** [comment]
I'm planning to use cwac-camera2 for image capturing

**Comment by diegoampessan** [comment]
nice!
