### ISSUE TITLE
Camera capture issue

### ISSUE THREAD

**Issue by nimitsolanki** [yazeed44/MultiImagePicker#31]
Hi , I'm having trouble with camera capture. Here is the logcat entry : 

java.lang.RuntimeException: Unable to resume activity {com.../net.yazeed44.imagepicker.ui.PickerActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=null} to activity {com.../net.yazeed44.imagepicker.ui.PickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3394)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3425)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4462)
            at android.app.ActivityThread.access$1000(ActivityThread.java:177)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
     Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=0, result=-1, data=null} to activity {com.../net.yazeed44.imagepicker.ui.PickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
            at android.app.ActivityThread.deliverResults(ActivityThread.java:4058)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3380)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3425)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4462)
            at android.app.ActivityThread.access$1000(ActivityThread.java:177)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
            at net.yazeed44.imagepicker.model.ImageEntry$Builder.from(ImageEntry.java:52)
            at net.yazeed44.imagepicker.model.ImageEntry.from(ImageEntry.java:26)
            at net.yazeed44.imagepicker.ui.PickerActivity.onActivityResult(PickerActivity.java:225)
            at android.app.Activity.dispatchActivityResult(Activity.java:6543)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:4054)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3380)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3425)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2763)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4462)
            at android.app.ActivityThread.access$1000(ActivityThread.java:177)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1454)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

How to hide/remove camera button ??

**Comment by yazeed44** [comment]
https://github.com/yazeed44/MultiImagePicker/issues/32
