### ISSUE TITLE
Rotation error ..

### ISSUE THREAD

**Issue by AbanoubAsaad** [yazeed44/MultiImagePicker#51]
After rotation while i'm in an album ... a null pointer exception happens when choose another album ..

**Comment by yazeed44** [comment]
Stacktrace

**Comment by AbanoubAsaad** [comment]
08-04 17:01:52.048    5471-5471/com.softxpert.android.fax E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.softxpert.android.fax, PID: 5471
    java.lang.NullPointerException: Attempt to read from field 'net.yazeed44.imagepicker.util.Picker net.yazeed44.imagepicker.util.Events$OnPublishPickOptionsEvent.options' on a null object reference
            at net.yazeed44.imagepicker.ui.ImagesThumbnailFragment.onCreateView(ImagesThumbnailFragment.java:35)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:458)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by AbanoubAsaad** [comment]
Hello yazeed ... 
Are you working on this issue ??

**Comment by yazeed44** [comment]
I just produced the bug , i will try to fix it

**Comment by yazeed44** [comment]
Ok i merged the fix to the master branch

Try to clone and run to see what happens ?

**Comment by AbanoubAsaad** [comment]
Good work yazeed .. thanks ..
but when will you update the repository ??

**Comment by yazeed44** [comment]
I might publish 1.2.0 today or tomorrow on gradle

**Comment by AbanoubAsaad** [comment]
any updates ??

**Comment by yazeed44** [comment]
I'm working on this feature https://github.com/yazeed44/MultiImagePicker/issues/33

Once i'm finished i will publish 1.2.0

**Comment by AbanoubAsaad** [comment]
I'm waiting for you .. :D :D 
Because I want to publish my new application on the store today ..

**Comment by yazeed44** [comment]
You can publish it , then when i update the lib all you need is to change my lib version in ```build.gradle```

It's rare for anyone to encounter this rotation bug anyway

**Comment by AbanoubAsaad** [comment]
No.. I prefer waiting until you finish :)

**Comment by AbanoubAsaad** [comment]
any updates ??

**Comment by yazeed44** [comment]
Sadly I got bitten by my own bad code :(

I don't think i might be able to publish it today , sorry

**Comment by yazeed44** [comment]
OK i published 1.2.0 , try it
https://github.com/yazeed44/MultiImagePicker/releases/tag/1.2.0

**Comment by AbanoubAsaad** [comment]
Good work yazeed ... thank you :)
