### ISSUE TITLE
when taking picture,bug hanppens

### ISSUE THREAD

**Issue by hjw541988478** [yazeed44/MultiImagePicker#54]
exception saving result to URI: file:///storage/emulated/0/capture1438926874060.png
    java.io.FileNotFoundException: Is a directory
            at android.os.Parcel.openFileDescriptor(Native Method)
            at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:253)
            at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:199)
            at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:916)
            at android.content.ContentResolver.openOutputStream(ContentResolver.java:686)
            at android.content.ContentResolver.openOutputStream(ContentResolver.java:662)
            at com.android.camera.PhotoModule.onCaptureDone(PhotoModule.java:1425)
            at com.android.camera.PhotoModule$10.onClick(PhotoModule.java:756)
            at android.view.View.performClick(View.java:4781)
            at android.view.View$PerformClick.run(View.java:19873)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5293)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

**Comment by hjw541988478** [comment]
MyDevice: Nexus5 + Android 5.1

**Comment by yazeed44** [comment]
I'd suggest you disable camera menu btn until i fix capturing problems

**Comment by yazeed44** [comment]
Try to clone the master branch then run it and see what happens please

**Comment by hjw541988478** [comment]
@yazeed44 great , works fine , but i use it in minsdk9 forcely.it looks alright now,could it trouble more ?

**Comment by yazeed44** [comment]
To be honest ```minSdkVersion = 15``` because of [cwac-cam2](https://github.com/commonsguy/cwac-cam2) , so that's a question you should ask the owner of cwac-cam2

Probably i will publish 1.2.0 today or tomorrow on gradle

**Comment by hjw541988478** [comment]
@yazeed44 maybe you can merge the source code and modify the minSdkVersion , I have already checkout your source code, modified the build.gradle manually and worked fine so far.

**Comment by yazeed44** [comment]
Did you try it on android below 15 ?

**Comment by hjw541988478** [comment]
I just have tested on 2.3.7,it seems everthing goes ok.

**Comment by yazeed44** [comment]
With capturing from camera ?

**Comment by hjw541988478** [comment]
Unluckily,I cann't see the camera button.

**Comment by yazeed44** [comment]
In the actionbar ? try to remove ```disableCaptureImageFromCamera``` if you call it in the builder
