### ISSUE TITLE
Android 6.0 FATAL EXCEPTION

### ISSUE THREAD

**Issue by klepov** [yazeed44/MultiImagePicker#85]
E/AndroidRuntime: FATAL EXCEPTION: CameraTwoEngine
                                                                                    Process: ru.*.*, PID: 1288
                                                                                    java.lang.UnsupportedOperationException: Exception when trying to write JPEG
                                                                                        at com.commonsware.cwac.cam2.JPEGWriter.process(JPEGWriter.java:99)
                                                                                        at com.commonsware.cwac.cam2.PictureTransaction.process(PictureTransaction.java:38)
                                                                                        at com.commonsware.cwac.cam2.CameraTwoEngine$TakePictureTransaction.onImageAvailable(CameraTwoEngine.java:686)
                                                                                        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:648)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                     Caused by: java.io.FileNotFoundException: /storage/emulated/0/captured_images/tmp1448637538855.png: open failed: EACCES (Permission denied)
                                                                                        at libcore.io.IoBridge.open(IoBridge.java:452)
                                                                                        at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
                                                                                        at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
                                                                                        at com.commonsware.cwac.cam2.JPEGWriter.process(JPEGWriter.java:77)
                                                                                        at com.commonsware.cwac.cam2.PictureTransaction.process(PictureTransaction.java:38) 
                                                                                        at com.commonsware.cwac.cam2.CameraTwoEngine$TakePictureTransaction.onImageAvailable(CameraTwoEngine.java:686) 
                                                                                        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:648) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                     Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
                                                                                        at libcore.io.Posix.open(Native Method)
                                                                                        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                                        at libcore.io.IoBridge.open(IoBridge.java:438)
                                                                                        at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
                                                                                        at java.io.FileOutputStream.<init>(FileOutputStream.java:72) 
                                                                                        at com.commonsware.cwac.cam2.JPEGWriter.process(JPEGWriter.java:77) 
                                                                                        at com.commonsware.cwac.cam2.PictureTransaction.process(PictureTransaction.java:38) 
                                                                                        at com.commonsware.cwac.cam2.CameraTwoEngine$TakePictureTransaction.onImageAvailable(CameraTwoEngine.java:686) 
                                                                                        at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:648) 
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                        at android.os.Looper.loop(Looper.java:148) 
                                                                                        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by solareye** [comment]
Hi
I guess it happened because you don't gave permission for write and read external storage
