### ISSUE TITLE
Crash on Samsung Galaxy S5

### ISSUE THREAD

**Issue by kailash-ratufa** [yazeed44/MultiImagePicker#97]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jaribha/net.yazeed44.imagepicker.ui.PickerActivity}: java.lang.NullPointerException: Attempt to read from field 'net.yazeed44.imagepicker.util.Picker net.yazeed44.imagepicker.util.Events$OnPublishPickOptionsEvent.options' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2658)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
       at android.app.ActivityThread.access$900(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by java.lang.NullPointerException: Attempt to read from field 'net.yazeed44.imagepicker.util.Picker net.yazeed44.imagepicker.util.Events$OnPublishPickOptionsEvent.options' on a null object reference
       at net.yazeed44.imagepicker.ui.PickerActivity.onCreate(PickerActivity.java:78)
       at android.app.Activity.performCreate(Activity.java:6221)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2611)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2723)
       at android.app.ActivityThread.access$900(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1422)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by mourjan** [comment]
I am getting this error as well, it is hard to reproduce, any news about it??


Fatal Exception: java.lang.NullPointerException
Attempt to read from field 'com.imagepicker.util.Picker com.imagepicker.util.Events$OnPublishPickOptionsEvent.a' on a null object reference

com.imagepicker.ui.AlbumsAdapter. (Unknown Source)
com.imagepicker.ui.AlbumsFragment.onRequestFailure (Unknown Source)
com.imagepicker.ui.AlbumsFragment.onRequestFailure (Unknown Source)
com.octo.android.robospice.request.notifier.DefaultRequestListenerNotifier$ResultRunnable.run........
